
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sun Feb 01 16:52:00 CST 2015
//----------------------------------------------------

package java_cup.simple_calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int MINUS = 4;
  static final int DIVIDE = 6;
  static final int UMINUS = 8;
  static final int NUMBER = 11;
  static final int MOD = 7;
  static final int SEMI = 2;
  static final int EOF = 0;
  static final int PLUS = 3;
  static final int error = 1;
  static final int RPAREN = 10;
  static final int TIMES = 5;
  static final int LPAREN = 9;
}

